//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopCalculatorWinFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyBinds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyBinds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopCalculatorWinFormsApp.KeyBinds", typeof(KeyBinds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnAns.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn+.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnDel.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnCos.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn0.
        /// </summary>
        internal static string D0 {
            get {
                return ResourceManager.GetString("D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn1.
        /// </summary>
        internal static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn2.
        /// </summary>
        internal static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn3.
        /// </summary>
        internal static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn4.
        /// </summary>
        internal static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn5.
        /// </summary>
        internal static string D5 {
            get {
                return ResourceManager.GetString("D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn6.
        /// </summary>
        internal static string D6 {
            get {
                return ResourceManager.GetString("D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn7.
        /// </summary>
        internal static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn8.
        /// </summary>
        internal static string D8 {
            get {
                return ResourceManager.GetString("D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn9.
        /// </summary>
        internal static string D9 {
            get {
                return ResourceManager.GetString("D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn..
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnCE.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn/.
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnExp.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnC.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMC.
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnM+.
        /// </summary>
        internal static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnM-.
        /// </summary>
        internal static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMS.
        /// </summary>
        internal static string F8 {
            get {
                return ResourceManager.GetString("F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMR.
        /// </summary>
        internal static string F9 {
            get {
                return ResourceManager.GetString("F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnLog.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn*.
        /// </summary>
        internal static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn+/-.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn0.
        /// </summary>
        internal static string NumPad0 {
            get {
                return ResourceManager.GetString("NumPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn1.
        /// </summary>
        internal static string NumPad1 {
            get {
                return ResourceManager.GetString("NumPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn2.
        /// </summary>
        internal static string NumPad2 {
            get {
                return ResourceManager.GetString("NumPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn3.
        /// </summary>
        internal static string NumPad3 {
            get {
                return ResourceManager.GetString("NumPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn4.
        /// </summary>
        internal static string NumPad4 {
            get {
                return ResourceManager.GetString("NumPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn5.
        /// </summary>
        internal static string NumPad5 {
            get {
                return ResourceManager.GetString("NumPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn6.
        /// </summary>
        internal static string NumPad6 {
            get {
                return ResourceManager.GetString("NumPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn7.
        /// </summary>
        internal static string NumPad7 {
            get {
                return ResourceManager.GetString("NumPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn8.
        /// </summary>
        internal static string NumPad8 {
            get {
                return ResourceManager.GetString("NumPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn9.
        /// </summary>
        internal static string NumPad9 {
            get {
                return ResourceManager.GetString("NumPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn^.
        /// </summary>
        internal static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn1/x.
        /// </summary>
        internal static string Oem5 {
            get {
                return ResourceManager.GetString("Oem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn..
        /// </summary>
        internal static string OemPeriod {
            get {
                return ResourceManager.GetString("OemPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn=.
        /// </summary>
        internal static string Oemplus {
            get {
                return ResourceManager.GetString("Oemplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn%.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSqrt.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn=.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSin.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn-.
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnTan.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
    }
}
