//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopCalculatorWinFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopCalculatorWinFormsApp.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn.
        /// </summary>
        internal static string BtnName {
            get {
                return ResourceManager.GetString("BtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DefaultResult {
            get {
                return ResourceManager.GetString("DefaultResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy | Paste.
        /// </summary>
        internal static string editSubItems {
            get {
                return ResourceManager.GetString("editSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string EqualSign {
            get {
                return ResourceManager.GetString("EqualSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI Light.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Calculator.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Desktop Calculator WinForms Application
        ///
        ///1.  To Perform a Binary Operation
        ///
        ///    1.1.  Input first operand by clicking on the numpad or through 
        ///            keyboard key press.
        ///    1.2.  Input operation that need to be performed (For binary 
        ///            operation the calculator will display the first operand and 
        ///            operator in a label).
        ///    1.3.  Input second operand &amp; press &apos;=&apos; to calculate the result.
        ///
        ///2.  To Perform a Unary Operation
        ///
        ///    2.1.  Input operand by clicking o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpContent {
            get {
                return ResourceManager.GetString("HelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Calculator Help.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC | M+ | M- | MS | M^.
        /// </summary>
        internal static string MemoryOperators {
            get {
                return ResourceManager.GetString("MemoryOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit | Exit | Help.
        /// </summary>
        internal static string menuItems {
            get {
                return ResourceManager.GetString("menuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR | M+ | M- | MS | MC | + | - | CE | C | Del | % | ^ | 1/x | * | / | 7 | 8 | 9 | Log | Exp | 4 | 5 | 6 | Sin | Cos | 1 | 2 | 3 | Tan | Sqrt | +/- | 0 | . | Ans | =.
        /// </summary>
        internal static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
    }
}
