//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopCalculatorWinFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopCalculatorWinFormsApp.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negation Button
        ///Input operator and press &quot;+/-&quot; to negate the number.
        ///Keyboard equivalent: N.
        /// </summary>
        internal static string btn___ {
            get {
                return ResourceManager.GetString("btn+/-", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Button
        ///Press &quot;0&quot; to include 0 to the operand.
        ///Keyboard equivalent: 0.
        /// </summary>
        internal static string btn0 {
            get {
                return ResourceManager.GetString("btn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Button
        ///Press &quot;1&quot; to include 1 to the operand.
        ///Keyboard equivalent: 1.
        /// </summary>
        internal static string btn1 {
            get {
                return ResourceManager.GetString("btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciprocal Operator
        ///Input operator and press &quot;\&quot; to reciprocate the number.
        ///Keyboard equivalent: \.
        /// </summary>
        internal static string btn1_x {
            get {
                return ResourceManager.GetString("btn1/x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Button
        ///Press &quot;2&quot; to include 2 to the operand.
        ///Keyboard equivalent: 2.
        /// </summary>
        internal static string btn2 {
            get {
                return ResourceManager.GetString("btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Button
        ///Press &quot;3&quot; to include 3 to the operand.
        ///Keyboard equivalent: 3.
        /// </summary>
        internal static string btn3 {
            get {
                return ResourceManager.GetString("btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Button
        ///Press &quot;4&quot; to include 4 to the operand.
        ///Keyboard equivalent: 4.
        /// </summary>
        internal static string btn4 {
            get {
                return ResourceManager.GetString("btn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Button
        ///Press &quot;5&quot; to include 5 to the operand.
        ///Keyboard equivalent: 5.
        /// </summary>
        internal static string btn5 {
            get {
                return ResourceManager.GetString("btn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Button
        ///Press &quot;6&quot; to include 6 to the operand.
        ///Keyboard equivalent: 6.
        /// </summary>
        internal static string btn6 {
            get {
                return ResourceManager.GetString("btn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Button
        ///Press &quot;7&quot; to include 7 to the operand.
        ///Keyboard equivalent: 7.
        /// </summary>
        internal static string btn7 {
            get {
                return ResourceManager.GetString("btn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 Button
        ///Press &quot;8&quot; to include 8 to the operand.
        ///Keyboard equivalent: 8.
        /// </summary>
        internal static string btn8 {
            get {
                return ResourceManager.GetString("btn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 Button
        ///Press &quot;9&quot; to include 9 to the operand.
        ///Keyboard equivalent: 9.
        /// </summary>
        internal static string btn9 {
            get {
                return ResourceManager.GetString("btn9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Button
        ///Press &quot;Ans&quot; to input previous result as operand.
        ///Keyboard equivalent: A.
        /// </summary>
        internal static string btnAns {
            get {
                return ResourceManager.GetString("btnAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Operator
        ///Press &quot;C&quot; to cancel recent operation.
        ///Keyboard equivalent: Esc.
        /// </summary>
        internal static string btnC {
            get {
                return ResourceManager.GetString("btnC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Entry Operator
        ///Press &quot;CE&quot; to cancel current entry of operand.
        ///Keyboard equivalent: Del.
        /// </summary>
        internal static string btnCE {
            get {
                return ResourceManager.GetString("btnCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine Operator
        ///Input operator and press &quot;Cos&quot; to find cos of a number.
        ///Keyboard equivalent: C.
        /// </summary>
        internal static string btnCos {
            get {
                return ResourceManager.GetString("btnCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Operator
        ///Press &quot;Del&quot; to remove the last inputted number.
        ///Keyboard equivalent: Backspace.
        /// </summary>
        internal static string btnDel {
            get {
                return ResourceManager.GetString("btnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent Operator
        ///Input operator and press &quot;Exp&quot; to find exponent to a number.
        ///Keyboard equivalent: E.
        /// </summary>
        internal static string btnExp {
            get {
                return ResourceManager.GetString("btnExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithm Operator
        ///Input operator and press &quot;Log&quot; to find log of a number.
        ///Keyboard equivalent: L.
        /// </summary>
        internal static string btnLog {
            get {
                return ResourceManager.GetString("btnLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Clear Button
        ///Press &quot;MC&quot; to clear the stored number.
        ///Keyboard equivalent: F5.
        /// </summary>
        internal static string btnMC {
            get {
                return ResourceManager.GetString("btnMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Read Button
        ///Press &quot;MR&quot; to read the stored number.
        ///Keyboard equivalent: F9.
        /// </summary>
        internal static string btnMR {
            get {
                return ResourceManager.GetString("btnMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Save Button
        ///Press &quot;MS&quot; to save the number.
        ///Keyboard equivalent: F8.
        /// </summary>
        internal static string btnMS {
            get {
                return ResourceManager.GetString("btnMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine Operator
        ///Input operator and press &quot;Sin&quot; to find sin of a number.
        ///Keyboard equivalent: S.
        /// </summary>
        internal static string btnSin {
            get {
                return ResourceManager.GetString("btnSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Root Operator
        ///Input operator and press &quot;Sqrt&quot; to its root.
        ///Keyboard equivalent: R.
        /// </summary>
        internal static string btnSqrt {
            get {
                return ResourceManager.GetString("btnSqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent Operator
        ///Input operator and press &quot;Tan&quot; to find tan of a number.
        ///Keyboard equivalent: T.
        /// </summary>
        internal static string btnTan {
            get {
                return ResourceManager.GetString("btnTan", resourceCulture);
            }
        }
    }
}
